import React from 'react';

const Disclaimer = () => {
  return (
    <div className="bg-white dark:bg-gray-800 max-w-5xl mx-auto my-6 px-4 py-6 md:px-8 md:py-8 rounded-xl shadow-lg">

      {/* <div className="bg-white dark:bg-gray-800 max-w-5xl mx-auto p-8 rounded-lg shadow-lg"> */}
      <h1 className="text-4xl font-bold text-gray-800 dark:text-gray-100 mb-6">Disclaimer</h1>
      <p className="text-lg text-gray-700 dark:text-gray-300 mb-4">
        Task Spinner is designed for fun, lighthearted use, and casual task generation among friends, pairs, or small groups.
      </p>
      <p className="text-lg text-gray-700 dark:text-gray-300 mb-6">
        By using this app, you agree to the following:
      </p>

      <ul className="list-disc list-inside text-lg text-gray-700 dark:text-gray-300 mb-6">
        <li className="mb-2">The tasks generated by the spinner are meant for entertainment and productivity purposes only.</li>
        <li className="mb-2">We are not responsible for how users choose to interpret or carry out any tasks generated by the app.</li>
        <li className="mb-2">Please use common sense and avoid any tasks that may be unsafe, inappropriate, or harmful in any situation.</li>
        <li className="mb-2">This app is not intended for children under 13 without parental guidance.</li>
      </ul>

      <p className="text-lg text-gray-700 dark:text-gray-300 mb-4">
        We aim to provide a positive and engaging experience. If you have any suggestions or concerns, feel free to contact us anytime.
      </p>

      <p className="text-lg text-gray-700 dark:text-gray-300 mb-6">
        Use responsibly. Have fun. Spin smart!
      </p>

      <div className="mt-8">
        <a href="/" className="mt-4">
          <button className="px-6 py-2 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 transition-colors">
            Back to Home
          </button>
        </a>
      </div>
    </div>
  );
};

export default Disclaimer;