export const tasks: Record<string, string[]> = {
  Romantic: [
    'Cook a candlelit dinner',
    'Write a love letter',
    'Plan a surprise date',
    'Create a photo album of memories',
    'Dance together to your favorite song',
    'Have a picnic under the stars',
    'Give each other massages',
    'Take a couples cooking class',
  ],
  Fun: [
    "Say your favorite movie line dramatically",
    "Invent a brand new dance move and name it",
    "Talk like a pirate for 30 seconds",
    "Make a superhero pose and hold it for 10 seconds",
    "Do 10 air high-fives to random directions",
    "Try to sneeze without making a sound (fake it if you must)",
    "Sing everything you say for the next minute",
    "Tell a short story using only emojis (act them out!)",
    "Pretend your hand is a puppet and give it a personality",
    "Make the weirdest noise you can (bonus if it’s unidentifiable)",
    "Give an Oscar-worthy speech for winning 'Best Laugh'",
    "Act like you’re stuck in a windstorm",
    "Say something really boring like it’s the most exciting thing ever",
    "Do your best impression of someone else in the room",
    "Invent a secret handshake with yourself",
    "Talk about your favorite food like it's a long-lost love",
    "Do a fake magic trick and try to convince everyone it's real",
    "Spell your name with your body (get creative!)"
  ],
  Casual: [
    "Act like you just saw a ghost",
    "Say your name backward and try to keep a straight face",
    "Walk across the room like you’re sneaking past a sleeping bear",
    "Pretend your shoe is a phone and take a call",
    "Describe your day in just one sound effect",
    "Snap your fingers to the beat of an imaginary song",
    "Do your best air guitar solo for 10 seconds",
    "Say the alphabet like you're on a rollercoaster",
    "Balance something on your head for 10 seconds",
    "Say 3 things you're grateful for—super fast",
    "Compliment someone in the most dramatic way possible",
    "Pretend you’re hosting a cooking show for 15 seconds",
    "Give a weather report for the room you're in",
    "Tell a joke, even if it’s terrible",
    "Pretend to be a celebrity giving an interview",
    "Spell your favorite snack out loud",
    "Act like your favorite animal for 5 seconds",
    "Give a motivational speech to your socks",
    "Make up a word and give it a definition",
    "Tell a short story that includes a banana, a spaceship, and a sneeze"
  ],
  Normal: [
    "Think of a word that starts and ends with the same letter",
    "Name 3 animals that live in the jungle",
    "Say two things that are square-shaped",
    "Name a song with a color in the title",
    "Think of something that’s both hot and cold",
    "Say a word that has double letters in it",
    "List 3 things that make noise",
    "Name something you can eat that starts with 'P'",
    "Say something that’s soft, hard, and in-between",
    "Name 3 things that use batteries",
    "Say 2 opposites in one sentence",
    "Name something that smells good and something that smells bad",
    "Think of something taller than you and smaller than your hand",
    "Say a made-up word and give it a meaning",
    "Name 3 things that roll",
    "Describe your day using only 3 nouns",
    "Say a color that’s also a fruit",
    "Name something that can fly and swim",
    "Name 3 things you can do with your eyes closed",
    "Make up a riddle and say it out loud"
  ],
};