export const tasks: Record<string, string[]> = {
  Romantic: [
    'Cook a candlelit dinner',
    'Write a love letter',
    'Plan a surprise date',
    'Create a photo album of memories',
    'Dance together to your favorite song',
    'Have a picnic under the stars',
    'Give each other massages',
    'Take a couples cooking class',
  ],
  Fun: [
    'Have a karaoke night',
    'Play a board game',
    'Go on a scavenger hunt',
    'Try a new hobby together',
    'Have a movie marathon',
    'Build a pillow fort',
    'Go roller skating',
    'Learn a TikTok dance',
  ],
  Casual: [
    'Take a walk in the park',
    'Get coffee together',
    'Watch the sunset',
    'Go window shopping',
    'Visit a farmers market',
    'Have a pizza night',
    'Play card games',
    'Browse a bookstore',
  ],
  Normal: [
    'Clean the house together',
    'Go grocery shopping',
    'Do the laundry',
    'Plan the weekly menu',
    'Organize a closet',
    'Water the plants',
    'Pay the bills',
    'Make a to-do list',
  ],
};